version: '3.7'

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - "9324:9324"
      - "4593:4593"
    environment:
      - SERVICES=s3,lambda,sqs,iam
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
      - DATA_DIR=./localstack/data
    volumes:
      - ./localstack/data:/var/lib/localstack #mount the localstack data folder to the container